//! The startup identity of a UDS run (D7 #1976): ephemeral, the named
//! `cli:<name>` session, or a fresh user-chat identity from composition's
//! generator — never generated by the interface.
use super::*;
use crate::interface::cli::CliContext;

#[test]
fn the_startup_identity_is_ephemeral_named_or_a_fresh_chat_key() {
    use crate::domain::session::USER_CHAT_PREFIX;
    let ctx = CliContext {
        sessions: Some(crate::composition::sessions::build_session_handles),
        retention: Some(crate::composition::sessions::build_retention_handles),
        catalogue: Some(crate::composition::catalogue::build_catalogue_handles),
        provider_runtime: Some(crate::composition::runtime::build_agent_provider),
        tool_policy_persistence: Some(
            crate::composition::tool_policy::build_tool_policy_persistence,
        ),
        fresh_session_identity: Some(crate::composition::sessions::build_fresh_session_identity),
        ..Default::default()
    };
    let flags = |args: &[&str]| {
        let mut stderr = String::new();
        let argv: Vec<String> = ["--mode", "uds"]
            .iter()
            .chain(args)
            .map(|s| s.to_string())
            .collect();
        parse_agent_flags(&argv, &mut stderr).unwrap()
    };
    let mut stderr = String::new();
    // No --session, not ephemeral → fresh user chat (chat- namespace).
    let fresh = resolve_startup_identity(&ctx, &flags(&[]), false, &mut stderr).unwrap();
    assert!(
        fresh.runtime_key().starts_with(USER_CHAT_PREFIX),
        "expected chat- key, got: {}",
        fresh.runtime_key()
    );
    let again = resolve_startup_identity(&ctx, &flags(&[]), false, &mut stderr).unwrap();
    assert_ne!(fresh, again, "two unnamed runs never share a key");
    // Explicit --session → cli: namespace, exactly the name given.
    let named =
        resolve_startup_identity(&ctx, &flags(&["-s", "subagent"]), false, &mut stderr).unwrap();
    assert_eq!(named.runtime_key(), "cli:subagent");
    // Ephemeral → empty key (no persistence), even with a generator composed.
    let ephemeral =
        resolve_startup_identity(&ctx, &flags(&["--no-session"]), true, &mut stderr).unwrap();
    assert!(ephemeral.is_ephemeral());
    assert!(stderr.is_empty(), "{stderr}");
}

#[test]
fn an_unnamed_chat_run_refuses_to_start_without_a_composed_identity_generator() {
    let tmp = tempfile::TempDir::new().unwrap();
    let ctx = CliContext {
        base_dir: Some(tmp.path().to_path_buf()),
        sessions: Some(crate::composition::sessions::build_session_handles),
        retention: Some(crate::composition::sessions::build_retention_handles),
        catalogue: Some(crate::composition::catalogue::build_catalogue_handles),
        provider_runtime: Some(crate::composition::runtime::build_agent_provider),
        tool_policy_persistence: Some(
            crate::composition::tool_policy::build_tool_policy_persistence,
        ),
        fresh_session_identity: None,
        ..Default::default()
    };
    let mut stderr = String::new();
    let flags = parse_agent_flags(&["--mode".to_string(), "uds".to_string()], &mut stderr).unwrap();
    assert_eq!(cmd_agent_uds(&ctx, flags, &mut stderr), 1);
    assert!(
        stderr.contains("fresh session identity generator not composed"),
        "{stderr}"
    );
}

#[test]
fn an_agent_run_refuses_to_start_without_a_composed_provider_runtime() {
    let tmp = tempfile::TempDir::new().unwrap();
    let ctx = CliContext {
        base_dir: Some(tmp.path().to_path_buf()),
        sessions: Some(crate::composition::sessions::build_session_handles),
        retention: Some(crate::composition::sessions::build_retention_handles),
        catalogue: Some(crate::composition::catalogue::build_catalogue_handles),
        fresh_session_identity: Some(crate::composition::sessions::build_fresh_session_identity),
        config_selection: Some(crate::composition::configuration::build_select_config),
        provider_runtime: None,
        ..Default::default()
    };
    let mut stderr = String::new();
    let flags = parse_agent_flags(&["--mode".to_string(), "uds".to_string()], &mut stderr).unwrap();
    assert_eq!(cmd_agent_uds(&ctx, flags, &mut stderr), 1);
    assert!(
        stderr.contains("agent: provider runtime capability not composed"),
        "{stderr}"
    );
}
