#!/usr/bin/env python3
"""Generate the swarm board's Python-repr Unicode tables (#2277 review L2).

The Rust board writes a member id in a task's `contact` as Python's
`repr()` does, which escapes every code point `str.isprintable()`
refuses. Most of those do not depend on the Unicode version and are
listed by hand in `python_value.rs`; the unassigned ones (category Cn)
do, so they come from this script, run with the Python whose board the
Rust board matches (3.14, Unicode 16.0).

Writes:
- quecto-agentic-harness/src/domain/swarm/python_unassigned.rs: the Cn
  ranges, as a flat array of inclusive (first, last) pairs;
- quecto-agentic-harness/tests/fixtures/python_nonprintable.txt: every
  code point `str.isprintable()` refuses (surrogates excepted: no Rust
  `char` holds one), as inclusive hex ranges, which the unit test sweeps
  `python_repr`'s table against.

Run from the repository root, then format the table:
    python3 scripts/gen-python-unicode-tables.py && cargo fmt --all
"""
import sys
import unicodedata

UNICODE = "16.0.0"
TABLE = "quecto-agentic-harness/src/domain/swarm/python_unassigned.rs"
FIXTURE = "quecto-agentic-harness/tests/fixtures/python_nonprintable.txt"


def ranges(included):
    """The inclusive ranges of code points `included` accepts."""
    found, start = [], None
    for point in range(0x110000):
        if included(point):
            if start is None:
                start = point
        elif start is not None:
            found.append((start, point - 1))
            start = None
    if start is not None:
        found.append((start, 0x10FFFF))
    return found


def surrogate(point):
    return 0xD800 <= point <= 0xDFFF


def main():
    if unicodedata.unidata_version != UNICODE:
        sys.exit(
            f"Python {sys.version.split()[0]} has Unicode {unicodedata.unidata_version}; "
            f"the tables are Unicode {UNICODE} (Python 3.14)"
        )
    unassigned = ranges(lambda point: unicodedata.category(chr(point)) == "Cn")
    refused = ranges(
        lambda point: not surrogate(point) and not chr(point).isprintable()
    )
    pairs = ", ".join(f"0x{first:04x}, 0x{last:04x}" for first, last in unassigned)
    with open(TABLE, "w", encoding="utf-8") as table:
        table.write(
            "//! The code points Unicode "
            + UNICODE
            + " has not assigned (category Cn),\n"
            "//! which Python 3.14's `str.isprintable` refuses and its `repr()`\n"
            "//! escapes (#2277 review L2). Generated by\n"
            "//! `scripts/gen-python-unicode-tables.py` with Python 3.14's\n"
            "//! `unicodedata`; do not edit by hand.\n\n"
            "/// Inclusive `(first, last)` ranges, flattened, in ascending order.\n"
            f"pub(super) const UNASSIGNED: [u32; {2 * len(unassigned)}] = [{pairs}];\n"
        )
    with open(FIXTURE, "w", encoding="utf-8") as fixture:
        fixture.write(
            f"# Code points Python 3.14 (Unicode {UNICODE}) str.isprintable() refuses,\n"
            "# surrogates excepted; inclusive hex ranges. Generated by\n"
            "# scripts/gen-python-unicode-tables.py; do not edit by hand.\n"
        )
        for first, last in refused:
            fixture.write(f"{first:04x} {last:04x}\n")
    print(f"{len(unassigned)} unassigned ranges, {len(refused)} refused ranges")


if __name__ == "__main__":
    main()
