//! Port type bridging the application's tool-execution concern with
//! whichever transport is wired up to serve an extension (currently
//! UDS, but this type is deliberately transport-agnostic).
//!
//! Clean-architecture note: keeping this here means the interface
//! layer (e.g. `src/interface/cli/uds_ext_protocol.rs`) doesn't have
//! to reach *down* into `infrastructure` to learn the shape of a
//! pending tool request. Both interface (producer of `execute_tool`
//! events) and infrastructure (producer of the invocation itself,
//! via `UdsExtensionTool`) can depend inward on this application
//! type, matching the canonical dependency-arrow direction.

use crate::domain::tool::ToolResult;

/// A single in-flight tool invocation, handed from a `Tool` impl
/// (infrastructure) to the transport wiring (interface) so the
/// transport can forward the call to the registered extension client
/// and, once a result arrives on `reply`, the `Tool::execute` future
/// wakes and resumes the agent loop.
///
/// This struct deliberately owns its data: the producer gives up
/// `reply` by value, the consumer sends at most one result.
pub struct ToolInvocation {
    /// Correlation id — generated by the invoker and echoed by the
    /// client in its `tool_result` so the oneshot can be matched.
    pub tool_call_id: String,
    /// Name of the tool being invoked.
    pub tool_name: String,
    /// Arguments payload — the LLM's JSON tool-call arguments.
    pub arguments: String,
    /// Deliver the `ToolResult` here.
    pub reply: tokio::sync::oneshot::Sender<ToolResult>,
}
